import { useRouter } from "next/router";
import { useState } from "react";
import { useEffect } from "react";
import styles from "../styles/Auth.module.scss";

import Header from "~/publicParts/header/Top";
import CenterImage from "~/publicParts/centerImage/CenterImage";
import Signup from "~/auth/mobile/signup/Wrap";
import Signin from "~/auth/mobile/signin/Wrap";
import Head from "next/head";

const auth = () => {
  const router = useRouter();

  const [page, setPage] = useState<string | string[]>();
  const [isLoading, setIsLoading] = useState<boolean>(false);

  useEffect(() => {
    setPage(router.query.name);
    if (!router.query.name) router.push("./");
  }, []);

  const changeIsLoading = (state) => {
    setIsLoading(state)
  }

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>{`${
          page === "signup" ? "Sign Up" : "Sign In"
        } - Hitokan`}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />

        <link rel="stylesheet" href="https://use.typekit.net/lfm3arh.css" />
      </Head>
      <Header />
      <CenterImage isLoading={isLoading} />
      {page === "signup" ? <Signup changeIsLoading={changeIsLoading} /> : ""}
      {page === "signin" ? <Signin changeIsLoading={changeIsLoading} /> : ""}
    </div>
  );
};

export default auth;
