import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "~/publicParts/header/Top";
import CenterImage from "~/publicParts/centerImage/CenterImage";
import { useRouter } from "next/router";

import { FcGoogle } from "react-icons/fc";
import {
  GoogleAuthProvider,
  onAuthStateChanged,
  signInWithRedirect,
} from "firebase/auth";
import { auth } from "lib/firebase";
import { useEffect, useState } from "react";

export default function Home() {
  const router = useRouter();

  const [isLoading, setIsLoading] = useState(false);

  const handleClick = async (page: string) => {
    if (page !== "google") {
      const query = {
        name: page,
      };

      router.push({ pathname: "auth", query: query }, "auth");
    } else {
      setIsLoading(true);
      const provider = new GoogleAuthProvider();
      await signInWithRedirect(auth, provider);
    }
  };

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Hitokan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="stylesheet" href="https://use.typekit.net/lfm3arh.css" />
      </Head>
      <div className={styles.container}>
        <Header />
        <CenterImage isLoading={isLoading} />
        <div className={styles.inner}>
          <div className={styles.buttons}>
            <button
              className={styles.signup}
              onClick={() => handleClick("signup")}
            >
              Sign up
            </button>
            <button
              className={styles.signin}
              onClick={() => handleClick("signin")}
            >
              Log in
            </button>
            <div className={styles.or}>or</div>
            <button
              className={styles.google}
              onClick={() => handleClick("google")}
            >
              <FcGoogle className={styles.image} />
              <p>Log in with Google</p>
              <div className={styles.space}></div>
            </button>
          </div>
        </div>
      </div>
      {isLoading ? <div className={styles.cover}></div> : ""}
    </div>
  );
}
